# Generated by Django 3.1.7 on 2022-01-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_auto_20220105_0842'),
        ('cooperatives', '0005_alter_parcelle_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='espece',
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='remplace',
        ),
        migrations.AlterField(
            model_name='detail_formation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detailplanting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='formation',
            name='observation',
        ),
        migrations.AddField(
            model_name='formation',
            name='observation',
            field=models.ManyToManyField(to='parametres.ObsMonitoring'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='observation',
        ),
        migrations.AddField(
            model_name='monitoring',
            name='observation',
            field=models.ManyToManyField(to='parametres.ObsMonitoring'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sous_section',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
