# Generated by Django 3.1.7 on 2022-01-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0007_auto_20220105_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='taux_mortalite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='taux_vitalite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
