# Generated by Django 3.1.7 on 2022-01-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0008_auto_20220105_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteur',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date/Année de Naissance'),
        ),
    ]
